name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Build Environment
        id: setup-build-env
        run: |
          echo "docker_image=${GITHUB_REPO,,}" >> $GITHUB_OUTPUT
        env:
          GITHUB_REPO: ${{ github.repository }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          labels: |
            org.opencontainers.image.source = "${{ github.server_url }}/${{ github.repository }}"
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ steps.setup-build-env.outputs.docker_image }}:latest,
            ${{ env.DOCKER_REGISTRY }}/${{ steps.setup-build-env.outputs.docker_image }}:${{ github.sha }}
